# Generated by Django 2.2.17 on 2021-03-12 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymethod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='authentication_method',
            field=models.CharField(blank=True, default='Keyln', max_length=100, null=True, verbose_name='인증방식'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_information_save_use_or_not',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='카드정보저장시사용여부'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(max_length=100, unique=True, verbose_name='결제수단'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='partial_cancellation_or_not',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='부분취소사용여부'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_use_or_not',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='SMS_결제사용여부'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='service_join_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='서비스등록일'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='service_use_or_not',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='결제서비스 사용여부'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='shipping_destination_use_or_not',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='배송지사용여부'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='store_type',
            field=models.CharField(blank=True, choices=[('ag', 'ag'), ('re', 're')], default='ag', max_length=2, null=True, verbose_name='가맹점유형'),
        ),
        migrations.AlterField(
            model_name='paymentmethodsettlementcycle',
            name='affiliate_withdrawal_use_or_not',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='가맹점출금여부'),
        ),
        migrations.AlterField(
            model_name='paymentmethodsettlementcycle',
            name='applied_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='적용일자'),
        ),
        migrations.AlterField(
            model_name='paymentmethodsettlementcycle',
            name='cycle',
            field=models.CharField(blank=True, choices=[('not_settled', 'not_settled'), ('immediately', 'immediately'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('D5', 'D5'), ('D6', 'D6'), ('D7', 'D7'), ('D8', 'D8'), ('D9', 'D9'), ('D10', 'D10'), ('D11', 'D11'), ('D12', 'D12'), ('D13', 'D13'), ('D14', 'D14'), ('D15', 'D15'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4')], default='D1', max_length=20, null=True, verbose_name='정산주기'),
        ),
        migrations.AlterField(
            model_name='paymentmethodsettlementcycle',
            name='settlement_wait_time',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='정산대기시간'),
        ),
    ]
