# Generated by Django 2.2.17 on 2021-04-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymethod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='store_type',
            field=models.CharField(blank=True, choices=[('ag', '대행'), ('re', '중계')], default='ag', max_length=2, null=True, verbose_name='가맹점유형'),
        ),
        migrations.AlterField(
            model_name='settlementinformation',
            name='cancel_function',
            field=models.CharField(blank=True, choices=[('cancel_possible', '취소 가능'), ('only_before_purchase', '매입전만 가능(계좌이체 취소)'), ('impossible', '취소 불가능')], default='cancel_possible', max_length=30, null=True, verbose_name='취소기능'),
        ),
        migrations.AlterField(
            model_name='settlementinformation',
            name='classification_of_issuing_tax_invoices',
            field=models.CharField(blank=True, choices=[('month', '월'), ('occasional', '수시'), ('semiannual', '반기'), ('quarter', '분기'), ('year', '연')], default='month', max_length=20, null=True, verbose_name='세금계산서발행구분'),
        ),
        migrations.AlterField(
            model_name='settlementinformation',
            name='fee_calculation_criteria',
            field=models.CharField(blank=True, choices=[('trim', '버림'), ('rounds', '반올림')], default='trim', max_length=30, null=True, verbose_name='수수료계산기준'),
        ),
        migrations.AlterField(
            model_name='settlementinformation',
            name='settlement_method',
            field=models.CharField(blank=True, choices=[('mid_settlement', 'MID 정산'), ('gid_settlement', 'GID 정산')], default='mid_settlement', max_length=30, null=True, verbose_name='정산방법'),
        ),
        migrations.AlterField(
            model_name='settlementinformation',
            name='settlement_type',
            field=models.CharField(blank=True, choices=[('next_day', '다음날 정산'), ('d_day', '당일 정산')], default='next_day', max_length=30, null=True, verbose_name='정산유형'),
        ),
        migrations.AlterField(
            model_name='settlementinformation',
            name='standard_for_issuance_of_tax_invoice',
            field=models.CharField(blank=True, choices=[('approved', '승인'), ('calculate', '정산'), ('purchase', '매입')], default='calculate', max_length=20, null=True, verbose_name='세금계산서발행기준'),
        ),
    ]
