# Generated by Django 2.2.17 on 2021-03-11 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paymethod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementinformation',
            name='paygouser',
            field=models.OneToOneField(help_text='유저', on_delete=django.db.models.deletion.PROTECT, related_name='settlement_informations', to=settings.AUTH_USER_MODEL),
        ),
    ]
