# Generated by Django 2.2.17 on 2021-03-15 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymethod', '0002_auto_20210312_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['-pk'], 'verbose_name': '결제서비스 정보', 'verbose_name_plural': '결제서비스 정보 목록'},
        ),
        migrations.AlterModelOptions(
            name='settlementaccount',
            options={'ordering': ['-pk'], 'verbose_name': '정산계좌', 'verbose_name_plural': '정산계좌 목록'},
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(max_length=100, verbose_name='결제수단'),
        ),
        migrations.AlterField(
            model_name='paymentmethodsettlementcycle',
            name='applied_date',
            field=models.DateField(default=datetime.date.today, verbose_name='적용일자'),
        ),
        migrations.AlterField(
            model_name='paymentmethodsettlementcycle',
            name='cycle',
            field=models.CharField(choices=[('not_settled', 'not_settled'), ('immediately', 'immediately'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('D5', 'D5'), ('D6', 'D6'), ('D7', 'D7'), ('D8', 'D8'), ('D9', 'D9'), ('D10', 'D10'), ('D11', 'D11'), ('D12', 'D12'), ('D13', 'D13'), ('D14', 'D14'), ('D15', 'D15'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4')], default='D1', max_length=20, verbose_name='정산주기'),
        ),
    ]
