# Generated by Django 2.2.17 on 2021-03-16 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymethod', '0003_auto_20210315_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementaccount',
            name='applied_date',
            field=models.DateField(default=datetime.date.today, verbose_name='적용일자'),
        ),
        migrations.AlterField(
            model_name='settlementaccount',
            name='end_date',
            field=models.DateField(default=datetime.datetime(9999, 12, 30, 0, 0), verbose_name='종료일자'),
        ),
    ]
