# Generated by Django 2.2.17 on 2021-04-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymethod', '0005_auto_20210415_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethodsettlementcycle',
            name='cycle',
            field=models.CharField(choices=[('not_settled', 'not_settled'), ('immediately', 'immediately'), ('not_select', '아무것도 아님'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('D5', 'D5'), ('D6', 'D6'), ('D7', 'D7'), ('D8', 'D8'), ('D9', 'D9'), ('D10', 'D10'), ('D11', 'D11'), ('D12', 'D12'), ('D13', 'D13'), ('D14', 'D14'), ('D15', 'D15'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4')], default='not_select', max_length=20, verbose_name='정산주기'),
        ),
    ]
