# Generated by Django 2.2.17 on 2021-02-02 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayGoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mid', models.CharField(max_length=10, unique=True, verbose_name='가맹점아이디_MID')),
                ('gid', models.CharField(max_length=10, verbose_name='가맹점아이디_GID')),
                ('mid_name', models.CharField(max_length=9, verbose_name='가맹점관리자_MID_name')),
                ('sub_homepage', models.URLField(blank=True, null=True, verbose_name='서브몰심사_URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화여부')),
                ('type', models.CharField(choices=[('f', '가맹점'), ('a', '에이전시'), ('s', '관리자')], default='f', max_length=1, verbose_name='타입')),
                ('email', models.EmailField(max_length=100, verbose_name='이메일')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='전화번호')),
                ('fax_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='팩스번호')),
                ('store_joined_date', models.DateField(auto_now_add=True, verbose_name='가맹점등록일자')),
                ('store_modified_date', models.DateField(auto_now=True, verbose_name='루멘페이고전산업데이트일')),
                ('transfer_or_not', models.BooleanField(default=False, verbose_name='이관여부')),
                ('published_or_not', models.BooleanField(default=False, verbose_name='수도여부')),
                ('pay_link_or_not', models.BooleanField(default=False, verbose_name='페이링크여부')),
                ('pg_info_auto_save_or_not', models.BooleanField(default=False, verbose_name='PG_정보자동저장')),
                ('delivery_pay_or_not', models.BooleanField(default=False, verbose_name='딜리버리페이여부')),
                ('agencies', models.ForeignKey(blank=True, help_text='에이전트', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='franchisee_to_agency', to=settings.AUTH_USER_MODEL, verbose_name='가맹점 소개 시킨 에이전트 목록')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('owners', models.ForeignKey(blank=True, help_text='사업자번호등록', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paygousers', to='owners.Owner')),
                ('paygocomputationalmanagers', models.ManyToManyField(help_text='전산 관리자', related_name='paygousers', to='owners.PayGoComputationalManager')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '관리자',
                'verbose_name_plural': '관리자 목록',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='AgencyUser',
            fields=[
            ],
            options={
                'verbose_name': '에이전시',
                'verbose_name_plural': '에이전시 목록',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('members.paygouser',),
        ),
        migrations.CreateModel(
            name='FranchiseeUser',
            fields=[
            ],
            options={
                'verbose_name': '가맹점주',
                'verbose_name_plural': '가맹점주 목록',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('members.paygouser',),
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_slip', models.CharField(blank=True, max_length=100, null=True, verbose_name='매출전표')),
                ('vat_notation', models.CharField(blank=True, max_length=100, null=True, verbose_name='부가세표기')),
                ('payment_notice', models.CharField(blank=True, max_length=100, null=True, verbose_name='결제공지')),
                ('modify_text', models.TextField(default='', verbose_name='변경사항')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='업데이트된날짜')),
                ('franchisee_user', models.ForeignKey(help_text='가맹점주메모', on_delete=django.db.models.deletion.PROTECT, related_name='memos', to='members.FranchiseeUser')),
            ],
            options={
                'verbose_name': '가맹점주 메모',
                'verbose_name_plural': '가맹점주 메모 목록',
                'ordering': ['-pk'],
            },
        ),
    ]
