# Generated by Django 2.2.17 on 2021-04-14 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paygouser',
            name='agencies',
            field=models.ForeignKey(blank=True, help_text='에이전트', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='franchisee_to_agency', to=settings.AUTH_USER_MODEL, verbose_name='가맹점 소개한 에이전트 목록'),
        ),
        migrations.AlterField(
            model_name='paygouser',
            name='boss_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='가맹점주 이름'),
        ),
        migrations.AlterField(
            model_name='paygouser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='아이디 활성화여부'),
        ),
    ]
