# Generated by Django 2.2.17 on 2021-02-05 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0005_auto_20210203_0934'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectPayGoUserManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='생성날짜')),
                ('manager', models.ForeignKey(help_text='매니저', on_delete=django.db.models.deletion.PROTECT, related_name='manager_to_user', to='owners.PayGoComputationalManager')),
                ('user', models.ForeignKey(help_text='페이고유저', on_delete=django.db.models.deletion.PROTECT, related_name='user_to_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
