# Generated by Django 2.2.17 on 2021-04-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paygouser',
            options={'ordering': ['-pk', 'user_type'], 'verbose_name': '관리자', 'verbose_name_plural': '관리자 목록'},
        ),
        migrations.AddField(
            model_name='paygouser',
            name='represent_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='유저 이름'),
        ),
    ]
