# Generated by Django 2.2.17 on 2021-03-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paygouser',
            name='mid',
        ),
    ]
