# Generated by Django 2.2.17 on 2021-04-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210414_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paygouser',
            name='boss_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='대표'),
        ),
    ]
