# Generated by Django 2.2.17 on 2021-04-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210416_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='paygouser',
            name='business_type',
            field=models.CharField(choices=[('coprerate', '법인사업자'), ('sole', '자영업'), ('non', '비사업자')], default=(('coprerate', '법인사업자'), ('sole', '자영업'), ('non', '비사업자')), max_length=10, verbose_name='사업체구분'),
        ),
    ]
