# Generated by Django 2.2.17 on 2021-03-15 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default='PAYGO164147963485', max_length=25, verbose_name='주문번호')),
                ('goods_name', models.CharField(max_length=50, verbose_name='상품_이름')),
                ('card_num', models.CharField(max_length=30, verbose_name='카드숫자')),
                ('card_pwd', models.CharField(max_length=2, verbose_name='카드비밀번호_앞자리_두개')),
                ('card_avail_year', models.CharField(max_length=4, verbose_name='카드_유효_연도')),
                ('card_avail_month', models.CharField(max_length=2, verbose_name='카드_유효_월')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('status', models.CharField(blank=True, choices=[('on_request', 'on_request'), ('approving', 'approving'), ('ok', 'ok'), ('cancel', 'cancel')], default='on_request', max_length=10, null=True, verbose_name='상태')),
                ('card_quota', models.CharField(max_length=2, verbose_name='할부개월')),
                ('buyer_name', models.CharField(max_length=20, verbose_name='구매자_이름')),
                ('buyer_auth_num', models.CharField(max_length=6, verbose_name='주민등록번호_앞자리')),
                ('buyer_tel', models.CharField(max_length=20, verbose_name='구매자_휴대폰번호')),
                ('buyer_email', models.CharField(max_length=50, verbose_name='구매자_이메일')),
                ('is_canceled', models.BooleanField(default=False)),
                ('payed_at', models.DateTimeField(auto_now_add=True)),
                ('canceled_at', models.DateTimeField(auto_now=True)),
                ('paygouser', models.ForeignKey(help_text='유저', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '결제 내역 정보',
                'verbose_name_plural': '결제 내역 정보 목록',
                'ordering': ['-pk'],
                'unique_together': {('paygouser', 'order_number', 'is_canceled')},
            },
        ),
    ]
