# Generated by Django 2.2.17 on 2021-03-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_number',
            field=models.CharField(default='PAYGO112348831147', max_length=25, verbose_name='주문번호'),
        ),
    ]
