# Generated by Django 2.2.17 on 2021-04-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_number',
            field=models.CharField(default='PAYGO111529275280', max_length=25, unique=True, verbose_name='주문번호'),
        ),
    ]
