# Generated by Django 2.2.17 on 2021-04-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210423_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_number',
            field=models.CharField(default='PAYGO111946726965', max_length=25, unique=True, verbose_name='주문번호'),
        ),
    ]
