# Generated by Django 2.2.17 on 2021-04-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210316_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_number',
            field=models.CharField(default='PAYGO173547061418', max_length=25, verbose_name='주문번호'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('on_request', 'on_request'), ('approving', 'approving'), ('ok', 'ok'), ('cancel', 'cancel')], default='on_request', max_length=10, verbose_name='상태'),
        ),
    ]
