# Generated by Django 2.2.17 on 2021-04-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210414_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='buyer_auth_num',
            field=models.CharField(max_length=6, verbose_name='주민등록번호 앞자리'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='buyer_email',
            field=models.CharField(max_length=50, verbose_name='구매자 이메일'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='buyer_name',
            field=models.CharField(max_length=20, verbose_name='구매자 이름'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='buyer_tel',
            field=models.CharField(max_length=20, verbose_name='구매자 휴대폰번호'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_avail_year',
            field=models.CharField(max_length=4, verbose_name='카드 유효 연도'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_pwd',
            field=models.CharField(max_length=2, verbose_name='카드비밀번호 앞자리 두개'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='goods_name',
            field=models.CharField(max_length=50, verbose_name='상품 이름'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='취소요청'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_number',
            field=models.CharField(default='PAYGO114343629073', max_length=25, verbose_name='주문번호'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='거래시점'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('on_request', '거래요청'), ('wait', '결제대기'), ('approving', '거래승인'), ('before_cancel', '매입전취소'), ('partial_cancel', '부분취소'), ('cancel', '거래취소')], default='on_request', max_length=10, verbose_name='거래상태'),
        ),
    ]
