# Generated by Django 2.2.17 on 2021-04-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20210415_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_number',
            field=models.CharField(default='PAYGO154847668206', max_length=25, verbose_name='주문번호'),
        ),
    ]
