# Generated by Django 2.2.17 on 2021-04-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20210416_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_number',
            field=models.CharField(default='PAYGO172510775222', max_length=25, verbose_name='주문번호'),
        ),
    ]
