# Generated by Django 2.2.17 on 2021-04-23 02:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectOwnerManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
            ],
        ),
        migrations.CreateModel(
            name='PayGoComputationalManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='담당자이름')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='담당자부서')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='담당자직책')),
                ('phone_number', models.CharField(max_length=100, verbose_name='담당자핸드폰번호')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='담당자_EMAIL')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='업데이트된날짜')),
            ],
            options={
                'verbose_name': '담당영업자',
                'verbose_name_plural': '담당영업자 목록',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_license_number', models.CharField(max_length=100, unique=True, verbose_name='사업자등록번호')),
                ('business_store_type', models.CharField(default='전자상거래', max_length=30, verbose_name='가게종목')),
                ('business_condition', models.CharField(default='서비스', max_length=30, verbose_name='업태')),
                ('business_open_date', models.DateField(blank=True, null=True, verbose_name='사업개시일')),
                ('business_capital_amount', models.IntegerField(blank=True, null=True, verbose_name='사업자본금')),
                ('business_url', models.URLField(blank=True, null=True, verbose_name='가맹점_URL')),
                ('business_representative_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='대표자명')),
                ('business_representative_birth', models.DateField(blank=True, null=True, verbose_name='대표자생년월일')),
                ('corporate_registration_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='법인등록번호')),
                ('business_representative_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='대표자_TEL')),
                ('business_representative_fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='대표자_FAX')),
                ('business_representative_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='대표자_EMAIL')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='계약일')),
                ('business_classification', models.CharField(max_length=100, verbose_name='사업체구분')),
                ('business_name', models.CharField(max_length=100, verbose_name='상호명')),
                ('business_main_item', models.CharField(max_length=100, verbose_name='주요판매물품')),
                ('application_route', models.CharField(max_length=100, verbose_name='접수경로')),
                ('sales_channel', models.CharField(blank=True, max_length=100, verbose_name='영업채널')),
                ('transaction_amount', models.IntegerField(blank=True, null=True, verbose_name='거래금액')),
                ('past_pg_company', models.CharField(blank=True, max_length=100, verbose_name='기존_PG사')),
                ('business_official_address', models.CharField(blank=True, max_length=100, verbose_name='사업장소재지')),
                ('business_real_address', models.CharField(blank=True, max_length=100, verbose_name='실사업장주소')),
                ('initial_registration_fee', models.IntegerField(default=0, verbose_name='초기등록비')),
                ('annual_management_fee', models.IntegerField(default=0, verbose_name='연_관리비')),
                ('guarantee_insurance_policy', models.BooleanField(default=True, verbose_name='보증보험증권')),
                ('reason_exemption', models.TextField(default='', verbose_name='면제사유')),
                ('call_contents', models.TextField(default='', verbose_name='통화내역')),
                ('contact_date_year_month', models.DateField(default=datetime.date.today, verbose_name='계약일자')),
                ('contact_date_month', models.DateField(default=datetime.date.today, verbose_name='계약예정월')),
                ('contact_receipt', models.BooleanField(default=False, verbose_name='계약서 수취')),
                ('contact_current_status', models.CharField(choices=[('ct_consult', '상담중'), ('ct_accept', '계약서접수'), ('rm_req', 'RM_심사요청'), ('rm_comp', 'RM_심사완료'), ('approve_req', '책임자승인요청'), ('approve_comp', '책임자승인완료'), ('approve_reject', '책임자승인반려'), ('contact_comp ', '계약완료')], default='ct_consult', max_length=15, verbose_name='계약현재상태')),
                ('contact_type', models.CharField(default='일반', max_length=100, verbose_name='계약서종류')),
                ('pdf1', models.FileField(blank=True, null=True, upload_to='users/pdf', verbose_name='PDF1')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='업데이트된날짜')),
                ('pay_managers', models.ManyToManyField(blank=True, help_text='사업자관리자', through='owners.ConnectOwnerManager', to='owners.PayGoComputationalManager')),
            ],
            options={
                'verbose_name': '사업자',
                'verbose_name_plural': '사업자 목록',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='connectownermanager',
            name='manager',
            field=models.ForeignKey(help_text='매니저', on_delete=django.db.models.deletion.PROTECT, related_name='manager_to_owner', to='owners.PayGoComputationalManager'),
        ),
        migrations.AddField(
            model_name='connectownermanager',
            name='owner',
            field=models.ForeignKey(help_text='사업자', on_delete=django.db.models.deletion.PROTECT, related_name='owner_to_manager', to='owners.Owner'),
        ),
    ]
