# Generated by Django 2.2.17 on 2021-03-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paygocomputationalmanager',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='담당자핸드폰번호'),
        ),
    ]
