# Generated by Django 2.2.17 on 2021-04-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='call_contents',
            field=models.TextField(default=' ', verbose_name='통화내역'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='reason_exemption',
            field=models.TextField(default=' ', verbose_name='면제사유'),
        ),
    ]
