# Generated by Django 2.2.17 on 2021-04-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_auto_20210423_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='call_contents',
            field=models.TextField(default='특이사항 없음', verbose_name='통화내역'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='reason_exemption',
            field=models.TextField(default='특이사항 없음', verbose_name='면제사유'),
        ),
    ]
