# Generated by Django 2.2.17 on 2021-02-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0004_auto_20210203_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectownermanager',
            name='owner',
            field=models.ForeignKey(help_text='사업자', on_delete=django.db.models.deletion.PROTECT, related_name='owner_to_manager', to='owners.Owner'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='pay_managers',
            field=models.ManyToManyField(blank=True, help_text='사업자관리자', through='owners.ConnectOwnerManager', to='owners.PayGoComputationalManager'),
        ),
    ]
